number: 4
name: Sintetizadores
tempo_config:
  min_bpm: 60
  max_bpm: 70
time_signature:
  beats_per_bar: 4
  beat_unit: 4
layers:
  - number: 1
    active: True
    channel: 1
    note_range_config:
      lower_key: "C-1"
      upper_key: "G9"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 0
    controller_changes:
      - continues_controller: "BANK_SELECT"
        min: 80
        max: 81
      - continues_controller: "BANK_SELECT_LSB"
        min: 0
        max: 3
      - continues_controller: "SUSTAIN"
        min: 0
        max: 127
        use_global_channel: True
      - continues_controller: "VOLUME"
        min: 0
        max: 127
      - continues_controller: "EXPRESSION"
        min: 0
        max: 127
  - number: 2
    active: True
    channel: 2
    note_range_config:
      lower_key: "C6"
      upper_key: "C8"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 0
    fix_velocity: 100
    controller_changes:
      - continues_controller: "BANK_SELECT"
        min: 80
        max: 81
      - continues_controller: "BANK_SELECT_LSB"
        min: 0
        max: 3
      - continues_controller: "SUSTAIN"
        min: 0
        max: 127
        use_global_channel: True
      - continues_controller: "VOLUME"
        min: 0
        max: 127
      - continues_controller: "EXPRESSION"
        min: 0
        max: 127
