number: 8
name: Salsa Azuquita - Fania - Prueba
tempo_config:
  min_bpm: 60
  max_bpm: 70
time_signature:
  beats_per_bar: 4
  beat_unit: 4
layers:
  - number: 1
    active: True
    channel: 1
    program: 006
    note_range_config:
      lower_key: "C-1"
      upper_key: "G9"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 0
    controller_changes:
      - continues_controller: "BANK_SELECT"
        min: 80
        max: 81
      - continues_controller: "BANK_SELECT_LSB"
        min: 0
        max: 3
      - continues_controller: "SUSTAIN"
        min: 0
        max: 127
        use_global_channel: True
      - continues_controller: "VOLUME"
        min: 0
        max: 127
      - continues_controller: "EXPRESSION"
        min: 0
        max: 127
  - number: 2
    active: True
    channel: 2
    note_range_config:
      lower_key: "C3"
      upper_key: "B4"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 85
      controller_changes:
        - continues_controller: "BANK_SELECT"
          min: 80
          max: 81
        - continues_controller: "BANK_SELECT_LSB"
          min: 0
          max: 3
        - continues_controller: "SUSTAIN"
          min: 0
          max: 127
          use_global_channel: False
        - continues_controller: "VOLUME"
          min: 0
          max: 127
        - continues_controller: "EXPRESSION"
          min: 0
          max: 127
  - number: 3
    active: True
    channel: 3
    octave: 2
    note_range_config:
      lower_key: "C3"
      upper_key: "B4"
    velocity_range_config:
      max_velocity: 105
      min_velocity: 90
      controller_changes:
        - continues_controller: "BANK_SELECT"
          min: 80
          max: 81
        - continues_controller: "BANK_SELECT_LSB"
          min: 0
          max: 3
        - continues_controller: "SUSTAIN"
          min: 0
          max: 127
          use_global_channel: False
        - continues_controller: "VOLUME"
          min: 0
          max: 127
        - continues_controller: "EXPRESSION"
          min: 0
          max: 127
  - number: 4
    active: True
    channel: 4
    note_range_config:
      lower_key: "C3"
      upper_key: "B4"
    velocity_range_config:
      max_velocity: 100
      min_velocity: 80
      controller_changes:
        - continues_controller: "BANK_SELECT"
          min: 80
          max: 81
        - continues_controller: "BANK_SELECT_LSB"
          min: 0
          max: 3
        - continues_controller: "SUSTAIN"
          min: 0
          max: 127
          use_global_channel: False
        - continues_controller: "VOLUME"
          min: 0
          max: 127
        - continues_controller: "EXPRESSION"
          min: 0
          max: 127
  - number: 5
    active: True
    channel: 5
    note_range_config:
      lower_key: "C3"
      upper_key: "B4"
    velocity_range_config:
      max_velocity: 127
      min_velocity: 95
      controller_changes:
      - continues_controller: "BANK_SELECT"
        min: 80
        max: 81
      - continues_controller: "BANK_SELECT_LSB"
        min: 0
        max: 3
      - continues_controller: "SUSTAIN"
        min: 0
        max: 127
        use_global_channel: False
      - continues_controller: "VOLUME"
        min: 0
        max: 127
      - continues_controller: "EXPRESSION"
        min: 0
        max: 127